version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "dev"

  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "./build-dev.sh"
    volumes:
      - .:/build
    ports:
      - "8081:8081"
    environment:
      - DEBUG=True
      - ADMIN_NAME=""
      - ADMIN_EMAIL=""
      - EMAIL_HOST=""
      - EMAIL_PORT=""
      - EMAIL_USERNAME=""
      - EMAIL_PASSWORD=""
      - DEFAULT_FROM_EMAIL=""
      - SERVER_EMAIL=""
      - ENVIRONMENT="LOCAL"
      - SECRET_KEY=2HY>fXi!dQ&(9Vf.XghCa;L6G=Ul4r-Bwqh>ae0RG3vIh1ZJ%T
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_NAME=database
      - ENVIRONMENT=LOCAL
    depends_on:
      - "database"

volumes:
  db:
