# Generated by Django 3.2.13 on 2022-06-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_encryption_indicator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.messageencryptionindicator",
            ),
            preserve_default=False,
        ),
    ]
