# Generated by Django 3.2.13 on 2022-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_message_message_encryption_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="public_key",
            field=models.CharField(default="Test", max_length=256),
            preserve_default=False,
        ),
    ]
