# Generated by Django 4.0.5 on 2022-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='on_chain_identity_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
