# Generated by Django 4.0.5 on 2022-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_identity_on_chain_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='public_key',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='message',
            name='public_key',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='message',
            name='signature',
            field=models.CharField(max_length=2048),
        ),
    ]
