# Generated by Django 4.0.5 on 2022-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_identity_public_key_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='fingerprint',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='on_chain_identity_number',
            field=models.IntegerField(unique=True),
        ),
    ]
