# Generated by Django 4.0.5 on 2022-06-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_identity_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='shared_secret_key',
            field=models.CharField(max_length=2048),
        ),
    ]
