# Generated by Django 4.0.5 on 2022-07-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_identity_shared_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='on_chain_identity_number',
            field=models.IntegerField(),
        ),
    ]
